version: '3.9'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'my_app_db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD:  'password'
    volumes:
      - .setup.sql:/docker-entrypoint-initbd.d/setup.sql
    ports:
      - '3306:3306'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
